[package]
name = "rtsc-derive"
version = "0.1.0"
edition = "2021"
authors = ["Serhij S. <div@altertech.com>"]
license = "Apache-2.0"
description = "Derive macros for RTSC"
repository = "https://github.com/roboplc/rtsc"
keywords = ["realtime", "robots", "plc", "industrial"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.13.0"

[dev-dependencies]
rtsc = "0.1"
